/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as SellerAccessRouteImport } from './routes/seller-access'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CreatePassportRouteImport } from './routes/create-passport'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PassportIdRouteImport } from './routes/passport.$id'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerAccessRoute = SellerAccessRouteImport.update({
  id: '/seller-access',
  path: '/seller-access',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatePassportRoute = CreatePassportRouteImport.update({
  id: '/create-passport',
  path: '/create-passport',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PassportIdRoute = PassportIdRouteImport.update({
  id: '/passport/$id',
  path: '/passport/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-passport': typeof CreatePassportRoute
  '/dashboard': typeof DashboardRoute
  '/seller-access': typeof SellerAccessRoute
  '/verify': typeof VerifyRoute
  '/passport/$id': typeof PassportIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-passport': typeof CreatePassportRoute
  '/dashboard': typeof DashboardRoute
  '/seller-access': typeof SellerAccessRoute
  '/verify': typeof VerifyRoute
  '/passport/$id': typeof PassportIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create-passport': typeof CreatePassportRoute
  '/dashboard': typeof DashboardRoute
  '/seller-access': typeof SellerAccessRoute
  '/verify': typeof VerifyRoute
  '/passport/$id': typeof PassportIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-passport'
    | '/dashboard'
    | '/seller-access'
    | '/verify'
    | '/passport/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-passport'
    | '/dashboard'
    | '/seller-access'
    | '/verify'
    | '/passport/$id'
  id:
    | '__root__'
    | '/'
    | '/create-passport'
    | '/dashboard'
    | '/seller-access'
    | '/verify'
    | '/passport/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreatePassportRoute: typeof CreatePassportRoute
  DashboardRoute: typeof DashboardRoute
  SellerAccessRoute: typeof SellerAccessRoute
  VerifyRoute: typeof VerifyRoute
  PassportIdRoute: typeof PassportIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller-access': {
      id: '/seller-access'
      path: '/seller-access'
      fullPath: '/seller-access'
      preLoaderRoute: typeof SellerAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-passport': {
      id: '/create-passport'
      path: '/create-passport'
      fullPath: '/create-passport'
      preLoaderRoute: typeof CreatePassportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passport/$id': {
      id: '/passport/$id'
      path: '/passport/$id'
      fullPath: '/passport/$id'
      preLoaderRoute: typeof PassportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreatePassportRoute: CreatePassportRoute,
  DashboardRoute: DashboardRoute,
  SellerAccessRoute: SellerAccessRoute,
  VerifyRoute: VerifyRoute,
  PassportIdRoute: PassportIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
